---
# Provice the URL and credentials to your Checkmk site here #
checkmk_var_server_url: "http://myserver/"
checkmk_var_site: "mysite"
checkmk_var_automation_user: "myuser"
checkmk_var_automation_secret: "mysecret"
checkmk_agent_user: "{{ checkmk_var_automation_user }}"
checkmk_agent_pass: "{{ checkmk_var_automation_secret }}"

checkmk_var_version: "2.3.0p6"
checkmk_var_edition: "cre"
#############################################################

# Set to true, to skip the break points:
checkmk_var_run_unattended: false
