---
checkmk_rules:

  - name: "Filesystem - Magic Factor."
    ruleset: "checkgroup_parameters:filesystem"
    rule:
      location:
        folder: "/"
        position: "bottom"
      conditions: {
        "host_labels": [],
        "host_tags": [],
        "service_labels": []
      }
      properties: {
        "comment": "{{ ansible_date_time.iso8601 }} - Ansible managed",
        "description": "",
        "disabled": false
      }
      value_raw: "{'magic': 0.8}"

  - name: "CPU - Load."
    ruleset: "checkgroup_parameters:cpu_load"
    rule:
      location:
        folder: "/"
        position: "bottom"
      conditions: {
        "host_labels": [],
        "host_tags": [],
        "service_labels": []
      }
      properties: {
        "comment": "{{ ansible_date_time.iso8601 }} - Ansible managed",
        "description": "",
        "disabled": false
      }
      value_raw: "{'levels': (1.0, 2.0)}"

  - name: "CPU - Utilization."
    ruleset: "checkgroup_parameters:cpu_iowait"
    rule:
      location:
        folder: "/"
        position: "bottom"
      conditions: {
        "host_labels": [],
        "host_tags": [],
        "service_labels": []
      }
      properties: {
        "comment": "{{ ansible_date_time.iso8601 }} - Ansible managed",
        "description": "",
        "disabled": false
      }
      value_raw: "{'core_util_time': (100.0, 300, 900), 'core_util_time_total': (100.0, 300, 900)}"

  - name: "Logwatch - Event Console Forwarding."
    ruleset: "checkgroup_parameters:logwatch_ec"
    rule:
      location:
        folder: "/"
        position: "bottom"
      conditions: {
        "host_labels": [],
        "host_tags": [],
        "service_labels": []
      }
      properties: {
        "comment": "{{ ansible_date_time.iso8601 }} - Ansible managed",
        "description": "",
        "disabled": false
      }
      value_raw: "{'facility': 17, 'method': '', 'monitor_logfilelist': False}"
