checkmk_ruleset: "checkgroup_parameters:memory_percentage_used"

checkmk_rule:
  conditions: {
    "host_labels": [],
    "host_name": {
      "match_on": [
        "test1.tld"
      ],
      "operator": "one_of"
    },
    "host_tags": [],
    "service_labels": []
  }
  properties: {
    "comment": "Warning at 80%\nCritical at 90%\n",
    "description": "Allow higher memory usage",
    "disabled": false,
    "documentation_url": "https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/main/plugins/modules/rules.py"
  }
  value_raw: "{'levels': (80.0, 90.0)}"
