---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  ## Only kept, as Debian 12 is not supported.
  - name: debian10
    image: geerlingguy/docker-debian10-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: debian11
    image: geerlingguy/docker-debian11-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    ## There are no Checkmk 2.0.0 server packages for Debian 12
    ## As these test also set up a server before testing the agent, we remove this image.
    # - name: debian12
    #   image: geerlingguy/docker-debian12-ansible
    #   command: ${MOLECULE_DOCKER_COMMAND:-""}
    #   tmpfs:
    #     - /run
    #   volumes:
    #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    #   privileged: true
    #   pre_build_image: true
  ## Only kept, as Rocky Linux 9 is not supported.
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: centos8
    image: geerlingguy/docker-centos8-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    ## There are no Checkmk 2.0.0 server packages for Rocky 9
    ## As these test also set up a server before testing the agent, we remove this image.
    # - name: rockylinux9
    #   image: geerlingguy/docker-rockylinux9-ansible
    #   command: ${MOLECULE_DOCKER_COMMAND:-""}
    #   tmpfs:
    #     - /run
    #   volumes:
    #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    #   privileged: true
    #   pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence  # disable for now, as we have non-idempotent tasks
    - side_effect
    - verify
    - cleanup
    - destroy
