---

- name: Get installed plugins
  shell: "ls {{ plugins_path }}/"
  register: plugin_list
  changed_when: false

- package_facts:
  when: by_package == true

- include_tasks: "Linux-search.yml"
  with_dict: "{{ cmk_plugin_base }}"
  loop_control:
    loop_var: plugin_name

- include_tasks: "Linux-install.yml"
  with_items: "{{ CMK_PLUGINS }}"
  loop_control:
    loop_var: needed_plugin
  when: CMK_PLUGINS|length > 0

- name: Get obsolete installed Plugins
  set_fact:
    plugin_list: "{{ plugin_list.stdout_lines | difference(CMK_PLUGINS) }}"

- include_tasks: "Linux-remove.yml"
  with_items: "{{ plugin_list }}"
  loop_control:
    loop_var: obsolete_plugin
  when: obsolete_plugin|length > 0

