---
# ansible-playbook playbooks/downtime_demo.yml
# ansible-playbook playbooks/downtime_demo.yml --skip-tags delete
# ansible-playbook playbooks/downtime_demo.yml --tags delete
- name: "create downtime"
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/config.yml
  vars:
    host_name: "{{ downtime_host }}"
  tasks:

  # services

  - name: "downtime 1 - on services with relative times"
    downtime:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      host_name: "{{ host_name }}"
      comment: downtime 1 - on services with relative timestamps
      start_after:
        hours: 2
        minutes: 30
      end_after:
        hours: 1
        minutes: 30
      service_descriptions:
        - "CPU utilization"
        - Memory

  - name: "downtime 2 - on services with absolute timestamps"
    downtime:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      host_name: "{{ host_name }}"
      comment: downtime 2 - on services with absolute timestamps
      start_time: 2024-03-25T20:39:28Z
      end_time: 2024-03-26T20:39:28Z
      service_descriptions:
        - "CPU utilization"
        - Memory

  - name: "downtime 3 - on services without timestamps"
    downtime:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      host_name: "{{ host_name }}"
      comment: downtime 3 - on services without timestamps
      service_descriptions:
        - "CPU utilization"
        - Memory
      end_after:
        minutes: 1

  # hosts

  - name: "downtime 4 - on host with relative times"
    downtime:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      host_name: "{{ host_name }}"
      comment: downtime 4 - on host with relative timestamps
      #start_time: 2022-03-25T20:39:28Z
      start_after:
        hours: 2
        minutes: 30
      end_after:
        hours: 1
        minutes: 30
      #force: yes

  - name: "downtime 5 - on host with absolute timestamps"
    downtime:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      host_name: "{{ host_name }}"
      comment: downtime 5 - on host with absolute timestamps
      start_time: 2024-03-25T20:39:28Z
      end_time: 2024-03-26T20:39:28Z

  - name: "downtime 6 - on host without timestamps"
    downtime:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      host_name: "{{ host_name }}"
      comment: downtime 6 - on host without timestamps

  # delete services downtimes

  - name: "downtime delete 1 - service downtimes"
    downtime:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      host_name: "{{ host_name }}"
      service_descriptions:
        - "CPU utilization"
        - Memory
      state: absent
    tags:
      - delete
  
  - name: "downtime delete 2 - host downtimes"
    downtime:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      host_name: "{{ host_name }}"
      state: absent
    tags:
      - delete