concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Lookup Module Rules

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - main
      - devel
    types:
      - opened
    paths:
      - 'plugins/lookup/rule.py'
      - 'plugins/lookup/rules.py'
  push:
    paths:
      - '.github/workflows/ans-int-test-lkp-rules.yaml'
      - 'plugins/lookup/rule.py'
      - 'plugins/lookup/rules.py'
      - 'plugins/module_utils/**'
      - 'tests/integration/files/includes/**'
      - 'tests/integration/targets/lookup_rules/**'

jobs:

  integration:
    name: "Integration Test"
    uses: ./.github/workflows/_template-ans-int-test.yaml
    with:
      module: lookup_rules
