concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Module Rule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - main
      - devel
    paths:
      - 'plugins/modules/rule.py'
  push:
    paths:
      - '.github/workflows/ans-int-test-rule.yaml'
      - 'plugins/modules/rule.py'
      - 'plugins/module_utils/**'
      - 'tests/integration/files/includes/**'
      - 'tests/integration/targets/rule/**'

jobs:

  integration:
    name: "Integration Test"
    uses: ./.github/workflows/_template-ans-int-test.yaml
    with:
      module: rule
