# README:
# - When changing the module name, it needs to be changed in 'env:MODULE_NAME' and in 'on:pull_requests:path'!
#
# Resources:
# - Template for this file: https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml
# - About Ansible integration tests: https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Lookup Module Folder
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:
    branches:
      - main
      - devel
    paths:
      - 'plugins/lookup/folder.py'
  push:
    paths:
      - '.github/workflows/ans-int-test-lkp-folder.yaml'
      - 'plugins/lookup/folder.py'
      - 'plugins/module_utils/**'
      - 'tests/integration/files/includes/**'
      - 'tests/integration/targets/lookup_folder/**'

jobs:

  integration:
    name: "Integration Test"
    uses: ./.github/workflows/_template-ans-int-test.yaml
    with:
      module: lookup_folder
